name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: npm run make

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy

      - name: Build app bundle
        run: cd android && gradle

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.base64
          base64 -d android/release.base64 > android/release.decrypted

      - name: Sign build
        run: jarsigner -keystore android/release.decrypted -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" android/app/build/outputs/bundle/release/app-release-signed.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
